---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tcp-go-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: tcp-go-echo
    spec:
      containers:
        - image: quay.io/skupper/tcp-go-echo
          name: tcp-go-echo
          imagePullPolicy: IfNotPresent
